### ISSUE TITLE
getDatabase() returns null on formHandle.php

### ISSUE THREAD

**Issue by Harry823** [yss-projectizza/YSS-WebsiteProject#9]

**Comment by Harry823** [comment]
Issue can be found on AutoFormHandle branch.

**Comment by tadeubarbosa** [comment]
It's not returning `null` for me :thinking: :

![image](https://user-images.githubusercontent.com/4499999/56982336-79205680-6b57-11e9-8b5c-737d3b602091.png)

See that I setted `display_errors` in PHP... Maybe if you set it too, the PHP return a error.

Code:

`````php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
`````
